name: publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5,17 * * *'
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-22.04
    container: quay.io/devfile/universal-developer-image:latest
    steps:
      - name: Checkout local code
        uses: actions/checkout@v4
        
      - name: Checkout che-website main branch
        uses: actions/checkout@v4
        with:
          repository: eclipse-che/che-website
          ref: main
          path: che-website
      - name: Build che-website to website/build/che
        run: node --version && yarn --version && yarn && yarn build
        working-directory: che-website

      - name: Checkout che-docs publication branch
        uses: actions/checkout@v4
        with:
          repository: eclipse-che/che-docs
          ref: publication
          path: che-docs  
      - name: Copy che-docs and chectl redirections to website/build/che
        run: |
          rm -rf che-docs/.git
          cp -R che-docs/* che-website/build/che
          cp -R static/* che-website/build/che
          
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./che-website/build/che
      #     publish_branch: publish
      #     force_orphan: false
